language: java
branches:
  only:
    - develop
    - /^release-[0-999].[0-999]$/
    - master
notifications:
  email:
    recipients:
    - hspichardo@gmail.com
script:
# Unit Test & Integration Test
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
